config/routes.rb
Rails.application.routes.draw do
  root to:'pages#home'

  get '/home' => 'pages#home'
  get '/feed' => 'pages#feed'
  get '/user_profile' => 'pages#user_profile'
  get '/add_photos' => 'pages#add_photos'
  post '/add_photos' => 'pages#add_photos'
  delete '/delete' => 'pages#delete'

  # devise_for :users
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    # confirmations: 'users/confirmations',
    # omniauthcallbacks: 'users/omniauthcallbacks',
    # passwords: 'users/passwords',
    # unlocks: 'users/unlocks'
  }
  # 
  # devise_for :installs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/' => 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_photo
  has_many_attached :images

  scope :by_time, -> { order(created_at: :dec) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, 
          :registerable,       
          :recoverable, 
          :rememberable, 
          :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :except => [:home]
  # before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery prepend: true
  helper_method :display_user_images
  
  def display_user_images
    @users = User.all
    if @users.any? 
      @users.each do |user|
        if user.images.attached?
          user.images.each do |image|
            image_tag image
          end
        end
      end
    end
  end
  # helper_method :user_signed_in?, :current_user
  # scope :user_session
  # :account_update, 
  # :new_user
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:account_update) { 
  #     |u| u.permit(:profile_photo, :email, :password, :password_confirmation, :current_password)
  #   }
  # end

  # def all_users_photos 
  #   all_photos = User.all.uploaded_photos
  # end

  

  def after_sign_in_path_for(resource)
    feed_path
  end

  def after_sign_out_path_for(resource)
    home_path
  end





end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticate_user!, :except => [:home]
  def home
   if after_sign_out_path_for(destroy_user_session_path)
   end
  end

  def user_profile 
  end

  def add_photos
    if params[:submit]
      # binding.pry

      current_user.images.attach(params[:user][:images])
      redirect_to user_profile_path
    end
  end

  def feed
   if after_sign_in_path_for(user_session_path)
    # all_users_photos
    @users = User.all
   else
    redirect_to new_user_registration
   end
  end

  def delete
    # binding.pry
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
  
    redirect_to feed_path
  end
  
  
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  def passthru
    super
  end

  # GET|POST /users/auth/twitter/callback
  def failure
    super
  end

  protected

  # The path used when OmniAuth fails
  def after_omniauth_failure_path_for(scope)
    super(scope)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end
  
  # POST /resource
  def create
    super
    current_user.profile_photo.attach(params[:user][:profile_photo])
    # binding.pry
  end

  # GET /resource/edit
  def edit
    super

  end

  # PUT /resource
  def update
    super
    current_user.profile_photo.attach(params[:user][:profile_photo])
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  #GET /resource/sign_in
  def new
    super
  end

  #POST /resource/sign_in
  def create
    super
  end

  #DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "box">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/add_photos.html.erb
<form enctype="multipart/form-data" action="/add_photos" class="new_photo" id="new_photo" method="post"><%= token_tag %> 
  <div class="form-row">
    <div class="form-group col-md-4">
      <label for="inputName">Photo</label>
      <input type="file" class="form-control" id="user_images" placeholder="Name" name= "user[images]" multiple>
    </div>

  <button type="submit" name="submit" class="btn btn-primary">Add Photo</button>
</form> 

app/views/pages/feed.html.erb
<h1> Some pictures will eventually go here!</h1>
   <% if current_user %>
      <%= current_user.email %> | <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete  %> |
      <%= link_to "Profile", user_profile_path %>
    <% else %>
      <%= link_to "SIGN UP", new_user_registration_path %> | <%= link_to "SIGN IN", new_user_session %>
    <% end %>
<div>
  <% if @users.any?  %>
    <% @users.each do |user| %>
      <% if user.images.attached? %>
        <% user.images.each do | image | %>
          <%=image_tag image %>
            <% if current_user && current_user.admin %>
              <%= link_to "Delete", { controller: "pages", action: "delete", id: image}, method: :delete %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Here's our home page!</h1>

<p> <%= link_to "Sign Up", new_user_registration_path %> </p>
<p> <%= link_to "Sign In", new_user_session_path %></p>


<p> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </p>

app/views/pages/user_profile.html.erb
<h1><%= current_user.email %></h1>
<div>
  <% if current_user.profile_photo.attached? %>
    <%= image_tag current_user.profile_photo %>
  <% end %>
</div>

<div>
  <% if current_user.images.attached? %>
    <% current_user.images.each do |image| %>
      <%= image_tag image%>
    <% end %>
  <% end %>
</div>

<p>user's pictures will go here!</p>

<%= link_to "Edit Profile", edit_user_registration_path %>
<%= link_to "Add Photos", add_photos_path %>
<%= link_to "Home", feed_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>